<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\user\Entity\User;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Implements hook_form_alter().
 */
function custom_user_fields_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'user_form') {
    \Drupal::service('custom_user_fields.custom_user_form_alter')->alterForm($form, $form_state, $form_id);
  }
}
